spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zgcbd
    username: root
    password: 123456

packFile:
  dir: D:\IDEAcode\zgcbd\src\main\resources\pack
  names: log.txt